"""Spec-conformance validator (``shelf_validate``).

Checks a shelf tree against its manifest and SPEC.md section 9. Read-only:
nothing on the shelf is created, fixed, or rewritten. The rule catalog and
severities mirror the spec; several rules are direct descendants of
``docshelf-mcp``'s ``doctor()`` (same names, same finding shape) so the
reference implementation and this validator report drift in one language.
"""

from __future__ import annotations

import json
import re
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

import yaml

from openshelf.engine.manifest import Manifest, ManifestError, load_manifest

__all__ = ["Finding", "validate_shelf", "parse_frontmatter"]

#: Footer marker emitted by the reference implementation's index generator.
DOCSHELF_INDEX_MARKER = "*Auto-generated by [docshelf-mcp]"

#: Files that are navigation/infrastructure, never documents.
SUBINDEX_FILENAME = "SUBINDEX.md"

LEDGER_HEADER = ["date", "episode_id", "mode", "approx_tokens_in", "digest_tokens", "notes"]
LEDGER_MODES = {"live", "import"}

EPISODE_KINDS = {"topic", "research", "session"}
EPISODE_REQUIRED_KEYS = ("id", "kind", "span", "tags", "approx_tokens")

_SPLIT_SECTION_RE = re.compile(r"^(\d{3,})-.+\.md$")
_RAW_GITHUB_RE = re.compile(r"https://raw\.githubusercontent\.com/([^/\s)]+)/([^/\s)]+)/")
_MD_RELATIVE_LINK_RE = re.compile(r"\]\((?!https?://|#)([^)\s]+\.md)\)")


@dataclass
class Finding:
    """One validation finding (SPEC.md section 9)."""

    rule: str
    severity: str  # "config-error" | "error" | "warning" | "info"
    path: str
    detail: str
    suggested_fix: str


def parse_frontmatter(text: str) -> dict[str, Any] | None:
    """Extract the episode frontmatter mapping, or None when absent.

    Per SPEC.md section 5.1 the frontmatter is the first ``---``-fenced YAML
    block, which MAY be preceded by a single H1 line and blank lines — live
    shelves carry the H1 first (the reference implementation prepends it on
    add), so a byte-0-only parser would reject every real episode.
    """
    lines = text.splitlines()
    i = 0
    # Skip leading blank lines and at most one H1 line.
    while i < len(lines) and not lines[i].strip():
        i += 1
    if i < len(lines) and lines[i].startswith("# "):
        i += 1
        while i < len(lines) and not lines[i].strip():
            i += 1
    if i >= len(lines) or lines[i].strip() != "---":
        return None
    start = i + 1
    end = None
    for j in range(start, len(lines)):
        if lines[j].strip() == "---":
            end = j
            break
    if end is None:
        return None
    try:
        data = yaml.safe_load("\n".join(lines[start:end]))
    except yaml.YAMLError:
        return None
    return data if isinstance(data, dict) else None


def validate_shelf(
    shelf_root: Path | str, manifest_path: Path | str | None = None
) -> dict[str, Any]:
    """Validate a shelf tree; returns the report dict (never raises for findings).

    Report shape::

        {status, shelf_root, spec_version, mode, verdict, finding_count, findings}

    ``verdict`` is ``config-error`` (manifest gate failed — SPEC 9.2 exit 2),
    ``violations`` (error findings — exit 1), or ``valid`` (exit 0; warnings
    and infos allowed).
    """
    shelf_root = Path(shelf_root).expanduser().resolve()
    try:
        manifest = load_manifest(shelf_root, manifest_path)
    except ManifestError as exc:
        finding = Finding(
            rule=exc.rule,
            severity="config-error",
            path="shelf.yml",
            detail=exc.detail,
            suggested_fix="create or fix shelf.yml so it passes shelf.schema.json",
        )
        return _report(shelf_root, None, [finding])

    findings = _collect_findings(manifest)
    return _report(shelf_root, manifest, findings)


def _report(shelf_root: Path, manifest: Manifest | None, findings: list[Finding]) -> dict[str, Any]:
    findings.sort(key=lambda f: (f.path, f.rule))
    if any(f.severity == "config-error" for f in findings):
        verdict = "config-error"
    elif any(f.severity == "error" for f in findings):
        verdict = "violations"
    else:
        verdict = "valid"
    return {
        "status": "ok",
        "shelf_root": str(shelf_root),
        "spec_version": manifest.spec_version if manifest else None,
        "mode": manifest.mode if manifest else None,
        "verdict": verdict,
        "finding_count": len(findings),
        "findings": [asdict(f) for f in findings],
    }


# ------------------------------------------------------------------ scanning


@dataclass
class _Category:
    """One scanned category: its directory plus resolved documents."""

    name: str  # "" for documents directly in docs_root (implicit root)
    dir: Path
    documents: list[Path]  # primary .md files (not sections, not SUBINDEX)
    split_dirs: list[Path]  # subdirs named after a sibling document stem
    orphan_dirs: list[Path]  # subdirs with no parent document


def _scan_dir(directory: Path, *, top_level: bool) -> _Category:
    md_files = sorted(p for p in directory.glob("*.md") if p.name != SUBINDEX_FILENAME)
    stems = {p.stem for p in md_files}
    split_dirs: list[Path] = []
    orphan_dirs: list[Path] = []
    for sub in sorted(p for p in directory.iterdir() if p.is_dir()):
        if sub.name in stems:
            split_dirs.append(sub)
        elif top_level:
            # At the docs root a non-split directory is a category, never an
            # orphan (whether it is declared is a separate rule).
            continue
        else:
            orphan_dirs.append(sub)
    name = "" if top_level else directory.name
    return _Category(
        name=name, dir=directory, documents=md_files, split_dirs=split_dirs, orphan_dirs=orphan_dirs
    )


def _scan_categories(manifest: Manifest) -> list[_Category]:
    """Scan the docs root into categories.

    Category directories are the direct children of the docs root; documents
    directly in the docs root form the implicit root category (legal when
    ``categories`` is not declared — SPEC 2). Directories named after a
    sibling document's stem are split-section dirs, not categories.
    """
    docs_root = manifest.docs_root_path
    categories: list[_Category] = []

    root_cat = _scan_dir(docs_root, top_level=True)
    categories.append(root_cat)

    root_doc_stems = {p.stem for p in root_cat.documents}
    for sub in sorted(p for p in docs_root.iterdir() if p.is_dir()):
        if sub.name in root_doc_stems:
            continue  # split dir of a root-level document
        categories.append(_scan_dir(sub, top_level=False))
    return categories


# ------------------------------------------------------------------- rules


def _collect_findings(manifest: Manifest) -> list[Finding]:
    findings: list[Finding] = []
    root = manifest.shelf_root

    def rel(p: Path) -> str:
        return p.relative_to(root).as_posix()

    # Reserved M1 surface: accepted, flagged, never enforced in v0.
    if manifest.mode == "multi":
        findings.append(
            Finding(
                "reserved-m1", "info", "shelf.yml",
                "mode: multi is reserved for M1 — v0 tooling does not enforce "
                "zones, leases, or provenance",
                "no action needed; multi semantics arrive in M1",
            )
        )
    elif manifest.has_agents or manifest.has_provenance:
        findings.append(
            Finding(
                "reserved-m1", "info", "shelf.yml",
                "agents/provenance fields are reserved for M1 and ignored in single mode",
                "no action needed",
            )
        )

    docs_root = manifest.docs_root_path
    if not docs_root.is_dir():
        findings.append(
            Finding(
                "docs-root-missing", "error", manifest.docs_root,
                f"docs_root '{manifest.docs_root}' does not exist",
                "create the directory or fix docs_root in shelf.yml",
            )
        )
        # Without a docs root no tree rule can run; file-level rules still can.
        _check_ledger_policy(manifest, findings)
        _check_index(manifest, [], findings)
        _check_docshelf_config(manifest, findings)
        return findings

    categories = _scan_categories(manifest)

    declared = manifest.categories
    if declared:
        declared_set = set(declared)
        for cat in categories:
            if cat.name and cat.name not in declared_set:
                findings.append(
                    Finding(
                        "category-undeclared", "error", rel(cat.dir),
                        f"category directory '{cat.name}' is not declared in "
                        "shelf.yml categories",
                        "declare the category in shelf.yml or move the directory",
                    )
                )
        existing = {cat.name for cat in categories}
        for name in declared:
            if name not in existing:
                findings.append(
                    Finding(
                        "empty-category", "info", f"{manifest.docs_root}/{name}",
                        f"declared category '{name}' has no directory",
                        "create the directory or drop it from categories",
                    )
                )

    all_documents: list[Path] = []
    for cat in categories:
        all_documents.extend(cat.documents)
        _check_category(manifest, cat, findings)

    if manifest.profile == "memory":
        for doc in all_documents:
            _check_episode(manifest, doc, findings)

    _check_ledger_policy(manifest, findings)
    _check_index(manifest, all_documents, findings)
    _check_remote(manifest, findings)
    _check_docshelf_config(manifest, findings)
    return findings


def _check_category(manifest: Manifest, cat: _Category, findings: list[Finding]) -> None:
    root = manifest.shelf_root

    def rel(p: Path) -> str:
        return p.relative_to(root).as_posix()

    label = cat.name or manifest.docs_root

    if cat.name and not cat.documents and not cat.split_dirs and not cat.orphan_dirs:
        findings.append(
            Finding(
                "empty-category", "info", rel(cat.dir),
                "category directory contains no documents",
                "add documents or remove the empty directory",
            )
        )

    # .meta.json — optional; when present it must parse and match files.
    meta_path = cat.dir / ".meta.json"
    meta: dict[str, Any] = {}
    if meta_path.is_file():
        try:
            loaded = json.loads(meta_path.read_text(encoding="utf-8"))
            meta = loaded if isinstance(loaded, dict) else {}
            if not isinstance(loaded, dict):
                raise json.JSONDecodeError("not an object", "", 0)
        except json.JSONDecodeError:
            findings.append(
                Finding(
                    "corrupt-meta", "warning", rel(meta_path),
                    ".meta.json is not a valid JSON object",
                    "fix or delete the file, then regenerate the index",
                )
            )
        else:
            for key in sorted(meta):
                if not (cat.dir / key).is_file():
                    findings.append(
                        Finding(
                            "stale-meta-entry", "warning", rel(meta_path),
                            f"entry '{key}' has no matching document file",
                            "prune the entry",
                        )
                    )

    # Split-layout drift rules describe the reference implementation's
    # layout (SPEC 4.3/9.1); shelves with an external/manual index generator
    # own their large-document layout, so the rules do not apply there.
    if manifest.index_generated_by == "docshelf-mcp":
        for orphan in cat.orphan_dirs:
            findings.append(
                Finding(
                    "orphaned-split-dir", "warning", rel(orphan),
                    "split directory has no parent document with the same stem",
                    "delete the directory or restore the parent document",
                )
            )

        # Split numbering: NNN-<slug>.md, zero-padded, contiguous from 001.
        for split_dir in cat.split_dirs:
            sections = sorted(
                p.name for p in split_dir.glob("*.md") if p.name != SUBINDEX_FILENAME
            )
            numbers: list[int] = []
            ok = bool(sections)
            for name in sections:
                m = _SPLIT_SECTION_RE.match(name)
                if not m:
                    ok = False
                    break
                numbers.append(int(m.group(1)))
            if ok and numbers != list(range(1, len(numbers) + 1)):
                ok = False
            if not ok:
                findings.append(
                    Finding(
                        "split-out-of-sync", "warning", rel(split_dir),
                        "section files do not follow contiguous NNN-<slug>.md "
                        "numbering starting at 001",
                        "re-split the parent document to regenerate its sections",
                    )
                )

    # duplicate-title within the category (meta title, else filename stem).
    by_title: dict[str, list[Path]] = {}
    for doc in cat.documents:
        entry = meta.get(doc.name)
        title = (
            entry.get("title", "") if isinstance(entry, dict) else ""
        ) or doc.stem
        by_title.setdefault(title.strip().lower(), []).append(doc)
    for _title, paths in sorted(by_title.items()):
        if len(paths) > 1:
            for doc in sorted(paths)[1:]:
                findings.append(
                    Finding(
                        "duplicate-title", "warning", rel(doc),
                        f"title duplicates another document in '{label}'",
                        "give one of the documents a distinct title",
                    )
                )


def _check_episode(manifest: Manifest, doc: Path, findings: list[Finding]) -> None:
    root = manifest.shelf_root
    path = doc.relative_to(root).as_posix()
    try:
        text = doc.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return
    fm = parse_frontmatter(text)
    if fm is None:
        findings.append(
            Finding(
                "episode-frontmatter-missing", "error", path,
                "memory-profile document has no frontmatter block "
                "(first ----fenced YAML block, optionally after an H1)",
                "add frontmatter with id/kind/span/tags/approx_tokens",
            )
        )
        return

    problems: list[str] = []
    for key in EPISODE_REQUIRED_KEYS:
        if key not in fm:
            problems.append(f"missing required field '{key}'")
    if "id" in fm and str(fm["id"]) != doc.stem:
        problems.append(f"id '{fm['id']}' does not equal the filename stem '{doc.stem}'")
    if "kind" in fm and fm["kind"] not in EPISODE_KINDS:
        problems.append(f"kind '{fm['kind']}' is not one of {sorted(EPISODE_KINDS)}")
    if "approx_tokens" in fm and not isinstance(fm["approx_tokens"], int):
        problems.append("approx_tokens is not an integer")
    if "tags" in fm and not isinstance(fm["tags"], list):
        problems.append("tags is not a list")
    if "mode" in fm and fm["mode"] not in LEDGER_MODES:
        problems.append(f"mode '{fm['mode']}' is not one of {sorted(LEDGER_MODES)}")
    if problems:
        findings.append(
            Finding(
                "episode-frontmatter-invalid", "error", path,
                "; ".join(problems),
                "fix the frontmatter per SPEC.md section 5.2",
            )
        )


def _check_ledger_policy(manifest: Manifest, findings: list[Finding]) -> None:
    ledger = manifest.shelf_root / manifest.ledger_path
    if ledger.is_file():
        _check_ledger_file(manifest, ledger, findings)
    elif manifest.profile == "memory":
        findings.append(
            Finding(
                "no-ledger", "info", manifest.ledger_path,
                "memory-profile shelf has no ledger",
                "create the ledger with its header on the first shelve",
            )
        )

    policy = manifest.shelf_root / manifest.policy_path
    if not policy.is_file():
        findings.append(
            Finding(
                "no-policy", "info", manifest.policy_path,
                "shelf has no redaction/PII policy file",
                "add POLICY.md stating the shelf's redaction rules",
            )
        )


def _check_ledger_file(manifest: Manifest, ledger: Path, findings: list[Finding]) -> None:
    path = ledger.relative_to(manifest.shelf_root).as_posix()
    try:
        lines = ledger.read_text(encoding="utf-8").splitlines()
    except OSError:
        return
    problems: list[str] = []
    if not lines or lines[0].split("\t") != LEDGER_HEADER:
        problems.append("header line does not match '" + "\t".join(LEDGER_HEADER) + "'")
    for n, line in enumerate(lines[1:], start=2):
        if not line.strip():
            continue
        cols = line.split("\t")
        if len(cols) != len(LEDGER_HEADER):
            problems.append(f"line {n}: expected {len(LEDGER_HEADER)} tab-separated columns")
            continue
        date, _episode_id, mode, tokens_in, digest_tokens, _notes = cols
        if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", date):
            problems.append(f"line {n}: date '{date}' is not YYYY-MM-DD")
        if mode not in LEDGER_MODES:
            problems.append(f"line {n}: mode '{mode}' is not one of {sorted(LEDGER_MODES)}")
        for col_name, value in (("approx_tokens_in", tokens_in), ("digest_tokens", digest_tokens)):
            if not value.isdigit():
                problems.append(f"line {n}: {col_name} '{value}' is not an integer")
    if problems:
        findings.append(
            Finding(
                "ledger-malformed", "error", path,
                "; ".join(problems[:10]) + ("; ..." if len(problems) > 10 else ""),
                "fix the ledger per SPEC.md section 4.4 (notes must not contain tabs)",
            )
        )


def _check_index(manifest: Manifest, documents: list[Path], findings: list[Finding]) -> None:
    index = manifest.shelf_root / manifest.index_path
    if not index.is_file():
        findings.append(
            Finding(
                "stale-index", "warning", manifest.index_path,
                "index file does not exist",
                "generate the index (rebuild_index in the reference implementation)",
            )
        )
        return
    try:
        text = index.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return

    if manifest.index_generated_by == "docshelf-mcp" and DOCSHELF_INDEX_MARKER not in text:
        findings.append(
            Finding(
                "index-hand-edited", "error", manifest.index_path,
                "index.generated_by is docshelf-mcp but the generator footer "
                "marker is absent — the file looks hand-written",
                "regenerate the index with rebuild_index, or declare "
                "generated_by: external/manual",
            )
        )

    stale: list[str] = []
    # Relative .md links must resolve on disk.
    for target in sorted(set(_MD_RELATIVE_LINK_RE.findall(text))):
        if not (manifest.shelf_root / target).is_file():
            stale.append(f"links to missing file '{target}'")
    # Every primary document should be mentioned (by filename) in the index.
    for doc in documents:
        if doc.name not in text:
            stale.append(f"document '{doc.relative_to(manifest.shelf_root).as_posix()}' is not listed")
    if stale:
        findings.append(
            Finding(
                "stale-index", "warning", manifest.index_path,
                "; ".join(stale[:10]) + ("; ..." if len(stale) > 10 else ""),
                "regenerate the index from the on-disk shelf state",
            )
        )


def _origin_owner_repo(shelf_root: Path) -> tuple[str, str] | None:
    """Best-effort (owner, repo) from ``.git/config`` — offline heuristic.

    Reads the file directly instead of shelling out to git, so validation
    works without a git binary and never mutates repo state.
    """
    config = shelf_root / ".git" / "config"
    if not config.is_file():
        return None
    url = ""
    in_origin = False
    try:
        for line in config.read_text(encoding="utf-8", errors="replace").splitlines():
            stripped = line.strip()
            if stripped.startswith("["):
                in_origin = stripped.replace('"', "") == "[remote origin]"
            elif in_origin and stripped.startswith("url"):
                _, _, value = stripped.partition("=")
                url = value.strip()
                break
    except OSError:
        return None
    if not url:
        return None
    tail = url
    if ":" in tail and "://" not in tail:  # scp-like: git@host:owner/repo.git
        tail = tail.split(":", 1)[1]
    else:
        tail = tail.split("://", 1)[-1]
        tail = tail.partition("/")[2]  # drop host[:port]
    parts = [p for p in tail.split("/") if p]
    if len(parts) < 2:
        return None
    owner, repo = parts[-2], parts[-1]
    return owner, repo.removesuffix(".git")


def _check_remote(manifest: Manifest, findings: list[Finding]) -> None:
    index = manifest.shelf_root / manifest.index_path
    if not index.is_file():
        return
    try:
        text = index.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return
    linked = {(owner, repo) for owner, repo in _RAW_GITHUB_RE.findall(text)}
    if not linked:
        return
    origin = _origin_owner_repo(manifest.shelf_root)
    if origin is None:
        return
    mismatched = sorted(f"{o}/{r}" for o, r in linked if (o, r) != origin)
    if mismatched:
        findings.append(
            Finding(
                "remote-mismatch", "warning", manifest.index_path,
                f"index raw URLs point at {', '.join(mismatched)} but "
                f"git origin is {origin[0]}/{origin[1]} — raw URLs do not "
                "follow repo renames",
                "regenerate the index with the current remote",
            )
        )


def _check_docshelf_config(manifest: Manifest, findings: list[Finding]) -> None:
    docshelf_json = manifest.shelf_root / ".docshelf.json"
    if not docshelf_json.is_file():
        return
    try:
        data = json.loads(docshelf_json.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return  # corrupt impl config is the implementation's problem, not the spec's
    if not isinstance(data, dict):
        return
    conflicts: list[str] = []
    impl_name = data.get("name", "")
    if manifest.name and impl_name and manifest.name != impl_name:
        conflicts.append(f"name: shelf.yml '{manifest.name}' vs .docshelf.json '{impl_name}'")
    impl_order = data.get("category_order") or []
    if manifest.categories and impl_order and set(impl_order) - set(manifest.categories):
        extra = sorted(set(impl_order) - set(manifest.categories))
        conflicts.append(f"category_order lists undeclared categories: {', '.join(extra)}")
    if conflicts:
        findings.append(
            Finding(
                "docshelf-config-conflict", "warning", ".docshelf.json",
                "; ".join(conflicts),
                "align .docshelf.json with shelf.yml — the manifest is the contract",
            )
        )
